### ISSUE TITLE
Compilation of gateware

### ISSUE THREAD

**Issue by FhtagnEast** [enjoy-digital/pcie_screamer#3]
Hello!
I just install Vivado 2019.1 and ran script pcie_injector.py.
After loading compiled gateware file to FPGA (via Vivado programmer), flashed  board doesn't connected via USB (USB LED doesn't blinking, PCIE LED blinking as normal).
So, I assume that generation of firmware isn't correct, but I can't find source of mistakes.
Can you help me with my issue?

**Comment by enjoy-digital** [comment]
Sorry for the late answer. The repository has been updated and you be able to re-build and load with `./pcie_screamer.py --build --load`. If the USB led is still not blinking, please get in touch with LambdaConcept since it could be a hardware issue. I'm closing this, but please re-open if you still have the issue.
